# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08dd405162cd3da55c8318fdedbf77e3cd331ee9c06e55e41b9bad82b08f3fb0086ff072f12d83196c6c380c117133e26ddd462f8d54df059ba25307ae3f7556

test:
  secret_key_base: bb70705cc81929df3b955aff5e8092604e2bee8433401d14c9f263cbfb3c355faca9c8fb0878d3c412d613c68948af67476559c59761b381c13afdcc0a22d40b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
